//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfk_pruyom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abiturients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abiturients()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string study { get; set; }
        public string school { get; set; }
        public string fathername { get; set; }
        public string fatherphone { get; set; }
        public string mothername { get; set; }
        public string motherphone { get; set; }
        public string workgroup { get; set; }
        public string information { get; set; }
        public string dormitory { get; set; }
        public System.DateTime appdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
