//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfk_pruyom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id { get; set; }
        public int abiturientid { get; set; }
        public int specialtyid { get; set; }
        public int priority { get; set; }
    
        public virtual Abiturients Abiturients { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
