//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bfk_pruyom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bfk_pruyomEntities : DbContext
    {
        public bfk_pruyomEntities()
            : base("name=bfk_pruyomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abiturients> Abiturients { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Pruyomusers> Pruyomusers { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
    }
}
